# Config
# ========================================================================================

# Uncomment and set the URL of your site (with protocol, e.g. `https://`)
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.
url:                   https://bibincnair.github.io

# Uncomment and set the "base URL" of your site.
# When your site is in a subdirectory, set to `/<name of directory>`,
# with a leading `/` but no trailing `/`. Use the empty string '' otherwise.
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.
# baseurl:               ''


# General settings
# ---------------------------------------------------------------------------------------

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang:                  ko-KR, en-US

# The title of your blog. Used in the sidebar and the browser tab.
title:                 Stochastic Scribbler ✨

timezone:              Asia/Seoul

# A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)
description:           "Collection on notes n stuff."

# A shorter description for the sidebar.
tagline:               ... ♪♪ Bibin's notes n stuff. <3

# A list of keywords for your blog
keywords:              ["Development", "C++", "Rust", "Jekyll"]

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/img/seattle.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name: Bibin
  # url:               https://twitter.com/mdo
  # email:             markdotto@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-include-cache

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
